on: # defines trigger event
  push:
    branches: [ main ]

jobs: # group of steps that run together
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. This step downloads your code onto the Ubuntu runner
      - name: Checkout code
        uses: actions/checkout@v5 

      # 2. To be able to Specify the Node version
      - name: Set Up Node
        uses: actions/setup-node@v5 
        with: 
          node-version: 20 
      
      # 3. Run Npm install
      - name: Install dependencies
        run: npm install

      # 4. Run Tests
      - name: Run Tests # Fixed: Removed the space before the colon
        run: npm test